project:
  type: book
  output-dir: docs       # HTML files will be placed in docs/ for GitHub Pages

book:
  title: "ECON 700"
  author: "Robert M. McNab"
  chapters:
    - index.qmd
    - about.qmd
    - part: "Module 1: Introduction to R"
      chapters:
        - mod-1-0-overview.qmd
        - mod-1-1-intro-to-data.qmd
        - mod-1-2-intro-to-r.qmd
        - mod-1-3-intro-to-r-variables.qmd
        # - mod-1-2-descriptive-stats.qmd
        # - mod-1-3-data-structures.qmd
    - part: "Module 2: Introduction to Descriptive Statistics"

execute:
  webR: true            # enables WebR chunks for interactive R in the browser

format:
  html:
    toc: true
    toc-location: right
    self-contained: false   # recommended for WebR to load JS modules correctly
    link-external-newwindow: true  # open all links in new tabs


