project:
  type: book
  output-dir: docs       # HTML files will be placed in docs/ for GitHub Pages

book:
  title: "ECON 700"
  author: "Robert M. McNab"
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - mcnab.qmd
        - about.qmd
    - part: "Introduction to R"
      chapters:
        - mod-1-0-overview.qmd
        - mod-1-1-intro-to-data.qmd
        - mod-1-2-intro-to-r.qmd
        - mod-1-3-intro-to-r-variables.qmd
        - mod-1-4-intro-to-r-dataframes.qmd
    - part: "Descriptive Statistics"
      chapters: 
        - mod-2-0-overview.qmd
        - mod-2-1-frequency.qmd
    - part: "Covariance and Correlation"
    - part: "Introduction to Probability"
    - part: "Discrete Probability"
    - part: "Continuous Probability"
    - part: "Sampling Distributions"
    - part: "Inference"

execute:
  webR: true            # enables WebR chunks for interactive R in the browser
  
filters:
  - webr                # activates the webR filter globally
  
webr:
  packages: [dplyr, ggplot2, knitr]

format:
  html:
    toc: true
    toc-location: right
    self-contained: false   # recommended for WebR to load JS modules correctly
    link-external-newwindow: true  # open all links in new tabs


