---
title: "Probability Rules"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    self-contained: false     # must be false when using webr
urlcolor: blue
filters:
  - webr
execute:
  webR: true
---

```{r setup, echo = FALSE, message = FALSE}

library(dplyr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(kableExtra, quietly = TRUE)
library(tidyquant, quietly = TRUE)

```

## Probability

We have already touched on the idea of probability.

We calculated the number of combinations of a lottery and one could ask what are the odds of having a winning lottery ticket in any given draw of the lottery. We have also discussed rolling a fair die and tossing a fair coin.

Probabilities, in general, must adhere to some basic rules. Each outcome of a random experiment is assigned a probability, each assigned probability must lie on the \[0,1\] interval, and the sum of the probabilities across the outcomes of an experiment must equal 1.

More formally:

1.  For a random experiment with sample space $s$, each outcome $o_i \in s$ must be assigned a probability of occurrence.

2.  The probability assigned to an outcome in the sample space, $P(o_i)$, must lie on the \[0,1\] interval, that is, $0 \le P(o_i) \le 1$.

3.  Given $n$ outcomes in $s$, the sum of probabilities must be equal to 1 or $\sum_i^n P(o_i) = 1$.

## Subjective Assessment

The quickest method of assigning probabilities is to subjectively assign to the outcomes in the sample space. For example, what is the probability of a random student at Old Dominion University having a height less than 60 inches, 70 inches, and 80 inches?

We don't have data readily on hand to compute these probabilities. In this case, the best we can do is to assign our own evaluations of the probabilities of occurrence of each outcome.

Of course, if three people are posed this question and assign their subjective probabilities, there is a strong likelihood that the subjective probabilities will not be in exact agreement. And, without data, we cannot determine which set of subjective probabilities are correct.

## Equal Outcomes

Assume that we have a random experiment with $n$ equally likely outcomes in the sample space.

The probability of any outcome occurring is $1/n$.

Returning to the 10-sided fair die, then the probability of any of the outcomes in the sample space is

$$P(s) = 1/10 = 0.1$$

Does this adhere to the rules of assigning probabilities?

First, each outcome in the sample space is assigned a probability of $1/10$.

Second, the probability of any outcome in the sample space is $1/10$ and we can state that $0 \le 1/10 \le 1$.

Third, if we sum the probabilities of each outcome across all outcomes then the resulting summmation is equal to 1 or $\sum_1^{10} 1/10 = 1$.

## Relative Frequency

Assume we have a random experiment with $n$ outcomes in the sample space. We can compute the probability of each outcome using the proportion of occurrence of each outcome to the total number of occurrences. In other words, the probability of an outcome $o_i$ is equal to ratio of the number of times $o_i$ occurs relative to the total number of occurrences across all outcomes.

In the following code, we create a data frame with the reactions to the administration of a drug. We calculate the relative frequency of each type of reaction by:

$$
P(Reaction_i) = \frac{Cases_i}{sum_{i=1}^{N} Cases_i}
$$

Based upon these relative frequencies, we would assign a probability of 21.8% to patients having no reaction to the administration of the drug. Likewise, we would assign a probability of 67.6% to patients having a mild reaction to the drug, and so on.

```{webr-r}

rm(list = ls())

#Create Tibble with Example Data

reactions <- tibble("reaction" = c("None", 
                                   "Mild", 
                                   "Moderate", 
                                   "Severe"),
                    "cases"    = c(2420, 
                                   7502, 
                                   1149, 
                                   32))

#Calculate relative frequencies
#Use scales function to convert relative frequencies from decimal to percent format

rel_freq <- reactions %>%
  mutate(rel_freq = scales::label_percent(a = 0.1)(cases / sum(cases)))

#Use kable function to output data frame to formatted table
#Align - left or center alignment of columns
#Col.names - use these column names instead of data frame names
#format.args - use a comma for large numbers, no scientific notation
#Caption - add a caption to the table

kable(rel_freq,
      align       = "lcc",
      col.names   = c("Drug Reaction", "Number of Cases", "Relative Frequency"),
      format.args = list(big.mark = ",", scientific = FALSE),
      caption     = "Relative Frequency Table")

```

## Complement

In the previous example, the sample space consisted of four outcomes: no reaction (None), a mild reaction (Mild), a moderate reaction (Moderate), and a severe reaction (Severe).

**An event is defined as a collection of outcomes in a sample space.**

For example, if we defined an event as having **any type of reaction**, then the event space would consist of three outcomes: Mild, Moderate, and Severe.

An event can consist of one outcome in the sample space up to all the outcomes in the sample space. Continuing our example, if one event is having any type of reaction to the administration of the drug, then there is also another event: not having any reaction to the drug in question.

We thus have two events:

-   Having a reaction $E$

-   Not having a reaction $E^c$ where $c$ denotes the complement.

We can more formally state this as:

1.  An event, $E_i$ consists of $n$ outcomes in sample space $s$ where $s$ has $N$ outcomes.

2.  The number of outcomes for $E_i$ is such that $1 \le n \le N$.

3.  The probability of $E_i$ is equal to sum of probabilities of all the outcomes in $E_i$ such that $P(E_i) = \sum_{i=1}^{n} o_i$.

4.  The probability of all the outcomes not in $E_i$ is equal to $P(E_i)^C = 1 - P(E_i) = 1 - \sum_{i=1}^n o_i$.

In the code below, we summarize the number of cases that had any reaction and calculate the relative frequency of the event. The probability of having any type of reaction to the administration of the drug is 78.2% and the complement, which is having no reaction to the administration of the drug, is $1 - 0.782 = 0.118$ or 11.8%.

```{webr-r}

rm(list = ls())

#Create Tibble with Example Data

reactions <- tibble("reaction" = c("None", 
                                   "Mild", 
                                   "Moderate", 
                                   "Severe"),
                    "cases"    = c(2420, 
                                   7502, 
                                   1149, 
                                   32))

#Calculate relative frequencies
#Use scales function to convert relative frequencies from decimal to percent format

rel_freq <- reactions %>%
  mutate(rel_freq = scales::label_percent(a = 0.1)(cases / sum(cases)))

event_reaction <- reactions %>%
  mutate(rel_freq = cases / sum(cases)) %>%
  filter(reaction != "None") %>%
  summarize(cases = sum(cases),
            rel_freq = scales::label_percent(a=0.1)(sum(as.numeric(rel_freq))))

kable(event_reaction,
      align       = "lc",
      col.names   = c("Cases in Event", "Relative Frequency"),
      format.args = list(big.mark = ",", scientific = FALSE),
      caption     = "Relative Frequency Table")
```

## Union

Assume that we have two events, **A** and **B**, where the two events are part of the sample space $s$ of a random experiment.

If we combine the two events, that is, we create the **union** of the two events.

**The union of A and B is an event containing all the sample outcomes of A and B and is:**

$$
A \cup B
$$

Let's return to the 10-sided die experiment.

Assume that event A consists of the outcomes $A \in \{1, 2, 3 \}$ and B is an event consisting of the outcomes $B \in \{9, 10 \}$.

The union of A and B, $A \cup B$ is an event consisting of the outcomes $A \cup B \in \{1, 2, 3, 9, 10 \}$.

Consider the same experiment where $C \in \{4, 6, 8 \}$ and $D \in \{4, 5, 8, 10 \}$.

What is the union of $C$ and $D$?

$$
C \cup D \in \{4, 5, 6, 8, 10\}
$$


## Intersection

Assume that we have two events, **C** and **D**, where the two events are part of the sample space $s$ of a random experiment.

If we select only those outcomes that occur in each event, that is, we create the **intersection** of the two events.

**The intersection of C and D is an event containing the sample outcomes belonging to both C and D and is denoted as:**

$$
C \cap D
$$

Recall from the previous discussion of the union of two events that $C \in \{4, 6, 8 \}$ and $D \in \{4, 5, 8, 10 \}$. 

The union of C and D is:

$$
C \cup D \in \{4, 5, 6, 8, 10\}
$$
The intersection of C and D is 

$$C \cap D \in \{4, 8 \}$$

## Mutually Exclusive Events

The **addition law** provides a method of computing the probability of the union of two events. First, note that the probability of the union of two events is not equal to the sum of the probabilities of each event unless the two events are **mutually exclusive**, that is, there are no outcomes in common between the two events.

In other words, if $A \cap B \in 0$ then $P(A \cup B) = P(A) + P(B)$.

Intuitively, if two elements contain no elements in common, then the probability of the two events occurring is equal to the sum of the probability of two events.

Assume a 52-card deck of cars. Let **A** consist of all the Kings in the deck while **B** consists of all the Queens.

$$A \in \{K_c, K_d, K_h, K_s \}$$

$$B \in \{Q_c, Q_d, Q_h, Q_s \}$$

There are no elements in common between the two events, that is,

$$A \cap B = 0$$

Given that A and B are mutually exclusive

$$$P(A) = 4/52 = 0.077$$

$$P(B) = 4/52 = 0.077$$

$$P(A \cup B) = P(A) + P(B) = 0.077 + 0.077 = 0.154$$

## Addition Rule

If two events are not mutually exclusive, then the probability of the union of the two events is equal to:

$$
P(A \cup B) = P(A) + P(B) - P(A \cap B)
$$

Since A and B share outcomes in common, then the probability of either event occurring is equal to the probability of each event occurring minus the probability that of A and B occurring. The subtraction of the intersection of the event avoids double-counting.

Returning to the 52-card deck example, what is the probability that a card is either a King or a Heart? There are 4 Kings in a deck and 13 Hearts in a deck. 1 of the 13 hearts in the deck is a King.

$$P(K)        = 4/52$$

$$P(H)        = 13/52$$

$$P(K \cap H) = 1/52$$

$$P(K \cup H) = P(K) + P(H) - P(K \cap H)$$

$$P(K \cup H) = 4/52 + 13/52 - 1/52 = 16/52 = 4/13 = 0.308$$

The probability of drawing a King or a Heart from a 52-card deck is 0.308 or 30.8%.
