---
title: "Module 1 Overview"
---

## Introduction

Welcome to **Module 1** of ECON 700.

In this module, you will be introduced to the R programming environment and its integrated interface, RStudio. You will learn how to install and navigate both tools while becoming familiar with R’s basic syntax and data types. You will also learn how to import, view, and explore datasets to build a foundational understanding of data handling in R. Finally, you will apply descriptive statistical techniques to perform initial data exploration and summarize key insights from the datasets. 

------------------------------------------------------------------------

## Learning Objectives

By the end of this module, you should be able to:

-   MLO 1: **Install** and navigate R and RStudio.\
-   MLO 2: **Identify** R’s basic syntax and data types.\
-   MLO 3: **Work** with variables and simple operations in R.\
-   MLO 4: **Explore** data frames and tibbles in R.\
-   MLO 5: **Apply** descriptive statistics for initial data exploration.

------------------------------------------------------------------------

## Required Texts

The following textbooks are available for free. Please select the links provided to access.

-   Barbara Illowsky and Susan Dean. [Introductory Statistics 2e](https://openstax.org/books/introductory-statistics-2e/pages/1-introduction). OpenStax. Chapter 1.

-   Rafael Irizarry. (2025). [Introduction to Data Science: Data Wrangling and Visualization with R](https://rafalab.dfci.harvard.edu/dsbook-part-1/). Chapters 1-2.

-   Hadley Wickham, Mine Cetinkaya-Rundel, and Garrett Grolemund. (2025) [R for Data Science](https://r4ds.hadley.nz/). Sections 1-19.

-   [Online R documentation](https://cran.r-project.org/manuals.html)

-   [RStudio Cheat Sheets](https://posit.co/resources/cheatsheets/)

------------------------------------------------------------------------

## Module To Do List

-   Complete the hands-on coding exercises embedded in each lesson (MLO 3,4)\
-   Use WebR to experiment directly in your browser (MLO 2, 3, 4)\
-   Complete the weekly class assignment (MLO 1-5)\
-   Take the weekly knowledge quiz (MLO 2-5)\

------------------------------------------------------------------------

## Lessons in this Module

-   [1.1 – Introduction to Economic Analysis](mod-1-1-intro-to-data.qmd)\
-   [1.2 – Introduction to R](mod-1-2-intro-to-r.qmd)\
-   [1.3 – Variables in R](mod-1-3-intro-to-r-variables.qmd)\
-   [1.4 - Data frames in R](mod-1-4-intro-to-r-dataframes.qmd)
-   [1.5 - Using Quarto in R](mod-1-5-quarto.qmd)

------------------------------------------------------------------------

Next: Start with [**Economic Analysis**](mod-1-1-intro-to-data.qmd).
